### PR TITLE
Tests lints

### PR DESCRIPTION
**Pull request by radekrepo**

### CODE REVIEW

**Review by Grigorij-Dudnik — CHANGES_REQUESTED** [review]
Thanks for your work @radekrepo ! 

Please remove CONTRIBUTING.md file (it been removed from repo lasly). Also, as you moved manual tests one folder deeper, you need to modify executor_scenario1.py in line 3, to  not receive parent folder as base folder of directory, but grandparent one.

**Comment by radekrepo** [comment]
one more edit to do:
- pyproject.toml to standardise treatment of issue codes (ignore issue codes standard acrosss .py files)
- run all manual test & single task coder & manager. Confirm it all ran

**Comment by radekrepo** [comment]
@Grigorij-Dudnik all files run now!

**Review by Grigorij-Dudnik — APPROVED** [review]
Looks good. Merging.

**Pull request merged**
